/** Minimal ABI for AmongUsRoles — keep in sync with inco/contracts/AmongUsRoles.sol */
export const AMONG_US_ROLES_ABI = [
  {
    type: 'constructor',
    inputs: [{ name: '_impostorCount', type: 'uint16' }],
  },
  {
    name: 'openMatch',
    type: 'function',
    stateMutability: 'payable',
    inputs: [{ name: 'expectedPlayers', type: 'uint16' }],
    outputs: [],
  },
  {
    name: 'join',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    name: 'assignRoles',
    type: 'function',
    stateMutability: 'payable',
    inputs: [],
    outputs: [],
  },
  {
    name: 'revealRole',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'who', type: 'address' }],
    outputs: [],
  },
  {
    name: 'reset',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    name: 'cancelMatch',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    name: 'forceCancel',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    name: 'expectedPlayers',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint16' }],
  },
  {
    name: 'myRoleHandle',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'bytes32' }],
  },
  {
    name: 'roleHandleOf',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'who', type: 'address' }],
    outputs: [{ type: 'bytes32' }],
  },
  {
    name: 'deckFee',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'size', type: 'uint16' }],
    outputs: [{ type: 'uint256' }],
  },
  {
    name: 'impostorCount',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint16' }],
  },
  {
    name: 'playerCount',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    name: 'playerAt',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'i', type: 'uint256' }],
    outputs: [{ type: 'address' }],
  },
  {
    name: 'isRevealed',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'who', type: 'address' }],
    outputs: [{ type: 'bool' }],
  },
  {
    name: 'state',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint8' }],
  },
  {
    name: 'matchId',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    name: 'host',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'address' }],
  },
  {
    name: 'seated',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'address' }],
    outputs: [{ type: 'bool' }],
  },
  {
    name: 'RolesAssigned',
    type: 'event',
    inputs: [
      { name: 'matchId', type: 'uint256', indexed: true },
      { name: 'players', type: 'uint16', indexed: false },
      { name: 'impostors', type: 'uint16', indexed: false },
    ],
  },
  {
    name: 'RoleRevealed',
    type: 'event',
    inputs: [
      { name: 'matchId', type: 'uint256', indexed: true },
      { name: 'player', type: 'address', indexed: true },
      { name: 'handle', type: 'bytes32', indexed: false },
    ],
  },
];
